on:
  push:
    branches:
      - *
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: buildpacks/github-actions/setup-pack@v5.7.1
      - run: pack build --builder docker.io/paketobuildpacks/builder-jammy-buildpackless-tiny --buildpack docker.io/paketobuildpacks/nodejs --publish --cache-image ch4s3r/mergeable:linux-amd64 ch4s3r/mergeable --platform linux/amd64
      - run: pack build --builder docker.io/paketobuildpacks/builder-jammy-buildpackless-tiny --buildpack docker.io/paketobuildpacks/nodejs --publish --cache-image ch4s3r/mergeable:linux-arm64 ch4s3r/mergeable --platform linux/arm64

